---

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.5
    environment:
    - TZ=America/New_York
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
    healthcheck:
      test: echo stat | nc zookeeper 2181
      interval: 30s
      timeout: 30s
      retries: 3

  kafka:
    container_name: kafka
    hostname: kafka
    image:  bitnami/kafka:2.8.1
    depends_on:
    - zookeeper
    environment:
    - TZ=America/New_York
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181/kafka
    - KAFKA_CFG_NUM_PARTITIONS=4
    - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    - KAFKA_CFG_MIN_INSYNC_REPLICAS=1
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    - KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE=true
    - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
    - KAFKA_HEAP_OPTS=-Xmx1024m -Xms1024m -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=kafka
    - JMX_PORT=9999
    healthcheck:
      test: JMX_PORT= kafka-topics.sh --list --bootstrap-server kafka:9092
      interval: 30s
      timeout: 30s
      retries: 3

  enhancer:
    container_name: enhancer
    hostname: enhancer
    image: agalue/producer-enhancer-go
    build: .
    depends_on:
    - kafka
    environment:
    - TZ=America/New_York
    - BOOTSTRAP_SERVER=kafka:9092

